name: Accessible MooDropMenu
author: mashalla
category: Widgets
tags: [menu, dropmenu, navigation, accessible]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.1

sources:
  - "Source/MooDropMenu.js"
  - "Source/demo.js"

