name: Accessible MooDropMenu
author: mashalla
category: Widgets
tags: [menu, dropmenu, navigation, accessible]
#docs: http://no-docs.de
demo: http://mashalla.github.com/dropmenu2
current: 1.0

sources:
  - "source/MooDropMenu.js"

