name: Accessible MooDropMenu
author: mashalla
category: Widgets
tags: [menu, dropmenu, navigation, accessible]
docs: http://mashalla.github.com/dropmenu/
#demo: http://no-demo.de
current: 1.0

sources:
  - "source/MooDropMenu.js"

