name: MooDropMenu2
author: mashalla
category: Accessible
tags: [menu, dropmenu,navigation]
demo: http://www.aryweb.nl/projects/MooDropMenu
docs: http://github.com/arian/MooDropMenu/blob/master/README.md
current: 1.7.1

sources:
  - "Source/MooDropMenu.js"

